apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app-spring
  labels:
    app: flight-app-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-app-spring
  template:
    metadata:
      labels:
        app: flight-app-spring
    spec:
      containers:
        - name: flight-app-spring
          image: abhishek624/kubernetes-spring-mysql-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "512Mi"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-user-password
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-user-username
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flight-app-spring
  labels:
    app: flight-app-spring
spec:
  type: NodePort
  selector:
    app: flight-app-spring
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
